theme: jekyll-theme-dinky
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
kramdown:
  parse_block_html: true

title: ramblings
description: for my own benefit
# favicon: favicon.ico
