theme: jekyll-theme-dinky
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

title: ramblings
description: for my own benefit
# favicon: favicon.ico

# added this so newlines in align mathjax enviroments work
compress_html:
  clippings: all
  blanklines: true
